# This file is @generated by tarina.lang CLI tool
# It is not intended for manual editing.

from tarina.lang.model import LangItem, LangModel


class LudoMatcher:
    list: LangItem = LangItem("ludo", "matcher.list")
    no_desc: LangItem = LangItem("ludo", "matcher.no_desc")
    last_cmd: LangItem = LangItem("ludo", "matcher.last_cmd")


class Ludo:
    matcher = LudoMatcher


class Lang(LangModel):
    ludo = Ludo
